### ISSUE TITLE
HEPiX workshop

### ISSUE THREAD

**Issue by janschill** [janschill/cern-solid-code-investigation#64]
> HEPiX Spring 2021 online Workshop
> The HEPiX forum brings together worldwide Information Technology staff, including system administrators, system engineers, and managers from High Energy Physics and Nuclear Physics laboratories and institutes, to foster a learning and sharing experience between sites facing scientific computing and data challenges.
> 
> Participating sites include BNL, CERN, DESY, FNAL, IHEP, IN2P3, INFN, IRFU, JLAB, KEK, LBNL, NDGF, NIKHEF, PIC, RAL, SLAC, TRIUMF, many other research labs and numerous universities from all over the world.

https://indico.cern.ch/event/995485/overview

### To-do

- [x] Decide on where Solid fits in *Scientific Programme*
- [x] Abstracts until February 5th
- [x] Make sure to understand the underling storage mechanism of Solid

### Category for our presentation/workshop:

> Storage & Filesystems
> This track discusses everything related to storage technologies and hardware and to file systems, in particular distributed file systems.
> 
> It also addresses data management and data privacy, topics that may evolve into a separate track in the future. Submissions to these areas are hence much encouraged, too.

### Abstract

https://codimd.web.cern.ch/s/Scqu3eYIL#
